;;; stage.ss — Build tier configuration (generated by Makefile)
;;; DO NOT EDIT — this file is overwritten by `make build` based on GSH_TIER.
;;; Tier: small — core shell + Gerbil eval
(export #t)
(import :jsh/registry
        :gerbil/expander)
(*jsh-tier* "small")
